### ISSUE TITLE
UX fixes

### ISSUE THREAD

**Issue by burymm** [nemascha/avondhu#3]
По внешнему виду все хорошо. Нужно еще немного структуру поправить, чтобы было именно UX мышление. 

- [x] для иконок использовать или спрайт или что лучше http://fontawesome.io/ что-то из токого
- [x] телефон должен быть ссылкой есть что-то типа phone: Или mobile:
- [x] для ссылок в хедере не очень подходит название icons - это же "горячее меню", лучше назвать как-то так
- [x] left-frame - не очень подходящее имя. Это больше относится просто к контейнеру, можно назвать как-то .text-container или просто контейнер, тоже самое касается center-frame, right-frame  - стили ничего не делают чтобы это было слева или справа. Они тянутся на 100%. а слева или справа - задается колонками
- [x] face-photo - всегда ли будут картинки с лицами? наверное нет.
- [x] картинки которые нужны всегда для сайта мы кладем в папку images, те что нужны для верстки и будут меняться кладем в папку pics. 
- [x] картинки которые справа - это скорее всего ссылки на статьи или еще куда-то. Поэтому следует сделать их ссылками.
- [x] добавить хоть один блок с ссылкой "see full story"

**Comment by nemascha** [comment]
чтобы появились иконки нужно прописывать в head <link rel="stylesheet" href=
"path/to/font-awesome/css/font-awesome.min.css"> (пример с сайта)? телефон
у меня был прописан так: <a class="contact-menu-link none-decor"
href="tel:+353(0)25-24451/24858"> <h1
class="contact-heading">Telephone:</h1><p
class="contact-text">+353(0)25-24451/24858</p> </a>

20 ноября 2017 г., 23:15 пользователь Mikalai <notifications@github.com>
написал:

**Comment by nemascha** [comment]
У меня же все правые картинки являются ссылками. Только не отдельно картинка, а и текст тоже

**Comment by burymm** [comment]
> У меня же все правые картинки являются ссылками. Только не отдельно картинка, а и текст тоже

Посмотри плз размеры ссылок через дебагер. Там проблема в том, что при наведенини на блок не попадаешь на картику, если ты добавишь урл, тогда не сможешь перейти. Нужно ссылку сделать чтобы она была размером на весь блок.

**Comment by burymm** [comment]
> картинки которые справа - это скорее всего ссылки на статьи или еще куда-то. Поэтому следует сделать их ссылками.

Уже работает, но картинку помещать в p не правильно. Можно как вариант сделать ховер на саму картинку. А лучше всего на ссылку растянуть по размеру ad-container-photo и ховер оставить только на ссылке.
